
name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: self-hosted

    env:
      TF_IN_AUTOMATION: true
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        run: |
          echo "Setting AWS credentials"
          export AWS_ACCESS_KEY_ID=${{ secrets.btuser_aws_key }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.btuser_aws_secret }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || env.TF_AUTO_APPLY == 'true'
        run: terraform apply -auto-approve tfplan
